version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - redis
      - db
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agworld
    ports:
      - "5432:5432"
